config/routes.rb
TraditOnRails::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "register" => "users#new", :as => "register"
  get "trade" => "trade#index", :as => "trade"
  get "account" => "users#index", :as => "account"
  root :to => "home#index"
  
  resources :users
  resources :sessions
  resources :trade

end

app/models/currency.rb
class Currency
  include Mongoid::Document
  
  #schema
  field :is_reference, type: Boolean
  field :name
  
  embeds_many :rates, store_as: "rate"#, :class_name => "Rates", :inverse_of => :currency, :autobuild => true
  accepts_nested_attributes_for :rates
  
  embeds_many :nested_currencies, store_as: "currencies"
  accepts_nested_attributes_for :nested_currencies
  
  #validation
  validates_presence_of :name
  validates_presence_of :is_reference
  validates_uniqueness_of :name
  
end

app/models/nested_currency.rb
class NestedCurrency
  include Mongoid::Document
  
  #schema
  field :name
  field :number, type: Integer
  
  embedded_in :user, :inverse_of => :nested_currencies
  
  #validation
  validates_presence_of :name, :on => :create
  validates_presence_of :number, :on => :create
  validates_uniqueness_of :name
end

app/models/rate.rb
class Rate
  include Mongoid::Document
  
  #schema
  field :date, type: DateTime
  field :value, type: Float
  
  embedded_in :currency, :inverse_of => :rates

  #validation
  validates_presence_of :value, :on => :create
  validates_presence_of :date, :on => :create
  
end

app/models/transaction.rb
class Transaction
  include Mongoid::Document
  
  #schema
  field :action, type: String
  field :amount_from, type: Integer
  field :amount_to, type: Integer
  field :email, type: String
  field :date, type: DateTime
  field :currency_from, type: String
  field :currency_to, type: String
  field :user, type: String
  field :rate_from, type: Float
  field :rate_to, type: Float
  
  #validation
  validates_presence_of :email
  
end

app/models/user.rb
class User
  include Mongoid::Document
  
  #schema
  field :firstname
  field :lastname
  field :email
  field :hashed_pwd
  field :salt

  embeds_many :nested_currencies, store_as: "currencies"
  accepts_nested_attributes_for :nested_currencies
  
  #attributes
  attr_accessible :email, :password, :password_confirmation, :firstname, :lastname
  attr_accessor :password, :password_confirmation
  
  #validation
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  #authentication method
  def self.authenticate(email, password)
    user = User.find_by(email: email)
    if user && user.hashed_pwd == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end
  
  #generate a salt and a hash
  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.hashed_pwd = BCrypt::Engine.hash_secret(password, salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  after_filter :discard_flash_if_xhr
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def discard_flash_if_xhr
    flash.discard if request.xhr?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #Home page
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  #login
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  #logout
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
  
end

app/controllers/trade_controller.rb
class TradeController < ApplicationController
  
  #main trade page
  def index
    @currencies = current_user.nested_currencies.all
    
    respond_to do |format|
      format.html #"index"
      format.json {render json: @currencies} #send user currencies info, in .json format
    end
    
  end
  
  #post a trade
  def create
    print RubyVM::InstructionSequence.disasm(method(:create))
      #get params from the ajax post
      currencyF_name = params[:currencyF]
      currencyT_name = params[:currencyT]
      quantityF = params[:quantity].to_i
      
      #take the "from" and the "to" rate
      ratesF = Currency.find_by(name: currencyF_name).rates.all
      ratesT = Currency.find_by(name: currencyT_name).rates.all
      
      #get the "to" quantity
      quantityT = (ratesF[0].value * quantityF) / ratesT[0].value
      quantityT = quantityT.round
     
      #update the "from" and "to" quantity
      user = current_user
      @currencies = user.nested_currencies.all
      @currencies.each do |currency|
        if currency.name == currencyF_name
           currency.update_attributes(number: currency.number - quantityF)
        end
        if currency.name == currencyT_name
          currency.update_attributes(number: currency.number + quantityT)
        end
        #save user into the db
        currency.save()
      end

    #create a transaction
    transaction = Transaction.new(
      action: "SELL",
      amount_from: quantityF,
      amount_to: quantityT,
      email: user.email,
      date: DateTime.now,
      currency_from: currencyF_name,
      currency_to: currencyT_name,
      user: user.id,
      rate_from: ratesF[0].value,
      rate_to: ratesT[0].value
    )
    #save transaction into the db
    transaction.save()
    #send back the trade partial page
    render :partial => 'trade'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #new account page
  def new
    @refcurrencies = Currency.all
    @user = User.new
    @user.nested_currencies.build
  end
  
  #create account page
  def create
    @user = User.new(params[:user])
    if @user.save
      params[:user][:nested_currencies_attributes].values.each do |currency|
        @user.nested_currencies << NestedCurrency.new(number: currency["number"] ,name: currency["name"])
      end
      user_saved = User.authenticate(@user.email, @user.password)
      if user_saved
        session[:user_id] = user_saved.id
        redirect_to root_url, :notice => "registered and logged in !"
      end
    else
      redirect_to register_url, :notice => "Error - input email and password"
    end
  end
  
  #account main page
  def index
    @user = current_user
    @transactions = Transaction.where(email: current_user.email)
    render "index"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def reload_flash
    page.replace "flash_messages", :partial => 'layouts/flash'
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nested_currencies_helper.rb
module NestedCurrenciesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trade_helper.rb
module TradeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home #index</h1>

<div>
	<%= image_tag "legoR.jpg" %>
</div>

<div class="twelve columns" style="margin-top:30px"> 

<div class="row">

    <div class="three columns">
      <div class="panel">
        <h5>Panel Title</h5>
        <p>This is a three columns grid panel with an arbitrary height.</p>
      </div>
    </div>
    <div class="six columns">
      <div class="panel">
        <h5>Panel Title</h5>
        <p>This is a six columns grid panel with an arbitrary height. Bacon ipsum dolor sit amet salami ham hock biltong ball tip drumstick sirloin pancetta meatball short loin.</p>
      </div>
    </div>
    <div class="three columns">
      <div class="panel">
        <h5>Panel Title</h5>
        <p>This is a three columns grid panel with an arbitrary height.</p>
      </div>
    </div>

  </div>

      <div class="panel">
        <h4>Get in touch!</h4>

        <div class="row">
          <div class="nine columns">
            <p>We'd love to hear from you, you attractive person you.</p>
          </div>
          <div class="three columns">
            <a href="#" class="radius button right">Contact Us</a>
          </div>
        </div>
      </div>

    </div>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
<div class="alert-box" style="text-align:center">
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<a href="" class="close">&times;</a>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
	<!--<![endif]-->
	<head>
		<meta charset="utf-8" />

		<!-- Uncomment to make IE8 render like IE7 -->
		<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

		<!-- Set the viewport width to device width for mobile -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<title><%= content_for?(:title) ? yield(:title) : "Tradit" %></title>

		<!-- Included CSS Files -->
		<%= stylesheet_link_tag "application" %>

		<!-- Included JS Files  -->
		<%= javascript_include_tag "application" %>

		<%= csrf_meta_tags %>
		
		<script>
			$(document).ready(function(){
            $("#loginBtn").click(function(e) {
                e.preventDefault()
                $("#loginModal").reveal();
      
        });
        })
		</script>
		
	</head>
	<body>
		<!-- Navigation -->
		<ul class="top-bar">
			<div class="row">
				<div class="twelve columns">
					<ul class="top-bar">
						<ul>
							<!-- Title Area -->
							<li class="name">
								<h1> <%= link_to "Tradit #onRails", root_path %> </h1>
							</li>
							<li class="toggle-topbar">
								<a href="#"></a>
							</li>
						</ul>
						<section>

							<% if current_user %>
							<ul class="left ">
								<li class="divider"></li>
								<li>
									<%= link_to "My account", account_path %>
								</li>
								<li class="divider"></li>
								<li>
									<%= link_to "Let's trade!", trade_path %>
								</li>
								<li class="divider"></li>
							</ul>
							<ul class="right">
								<li>
									<%= link_to current_user.email %>
								</li>
								<li class="divider"></li>
								<li>
									<%= link_to "Log out", logout_path %>
								</li>
								<li class="divider"></li>
							</ul>
							<% else %>
							<ul class="right">
								<li>
									<%= link_to "Sign up", register_path %>
								</li>
								<li>
									<a href="" id="loginBtn">Log in</a>
								</li>
							</ul>

							<% end %>
						</section>
					</ul>
				</div>
			</div>
		</ul>
		<!-- End Navigation -->

		<div class="row">

			<div class="twelve columns">

				<div id="flash_messages">
					<%= render :partial => "layouts/flash", :locals => {:flash => flash} %>
				</div>

				<%= yield %>

				<!-- Footer -->

				<footer class="row">
					<div class="twelve columns">
						<hr>
						<div class="row">

							<div class="six columns">
								<p>
									© Copyright no one at all. Go to town.
								</p>
							</div>

							<div class="six columns">
								<ul class="link-list right">
									<li>
										<a href="#">Home</a>
									</li>
								</ul>
							</div>

						</div>
					</div>
				</footer>

				<!-- End Footer -->

			</div>
		</div>
		<%= render :partial => "sessions/new" %>
	</body>
</html>

app/views/trade/_trade.html.erb
<%= javascript_include_tag "trade_partial" %>

<div id="alert-box" class="alert-box" style="text-align:center">
	<div id="flash_notice">Traded!</div>
	<a href="" class="close">&times;</a>
</div>

<div id="alert-box-alert" class="alert-box alert" style="text-align:center">
	<div id="flash_notice">Error - info missing!</div>
	<a href="" class="close">&times;</a>
</div>

<h4>#Trade</h4>

<label>Action</label>
<select name="user[action]" disabled="true">
	<option>-- action --</option>
	<option>BUY</option>
	<option selected="selected">SELL</option>
</select>
<br/>
<br/>

<label>Currency</label>
<select id="currency_from_select">
	<option>-- currency --</option>
	<% for currency in @currencies %>
	<option value="<%= currency.name %>" ><%= currency.name %></option>
	<% end %>
</select>
<br/>
<br/>

<label>Amount</label>
<select id='quantity_select'>
	<option>-- quantity --</option>
</select>
<br/>
<br/>

<label>Currency</label>
<select id="currency_to_select">
	<option>-- currency --</option>
	<% for currency in @currencies %>
	<option value="<%= currency.name %>"><%= currency.name %></option>
	<% end %>
</select>
<br/>
<br/>

<input id="tradeBtn" type="submit" value="GO!" class="button" />

app/views/trade/index.html.erb
<%= javascript_include_tag "socket.io", "smoothie", "trade" %>

<h1>Trade #index</h1>

<div class="row">

	<div class="twelve columns panel">
		<h4>#Info</h4>
		<h5>Live rate</h5>
		<dic class="row">
			<div class="four columns">
				<label id="currencylive1">#loading</label>
			</div>
			<div class="four columns">
				<label id="currencylive2">#loading</label>
			</div>
			<div class="four columns">
				<label id="currencylive3">#loading</label>
			</div>
			<br/>
			<h5>My wallet</h5>
			<dic class="row">
				<% for currency in @currencies %>
				<div class="four columns">
					<label style="font-weight:bold" id="<%= currency.name %>label"><%= currency.name %>: <%= currency.number %></label>
				</div>
				<% end %>
	</div>
</div>

<div class="row">
	<div class="seven columns panel">
		<h4>#Live graph</h4>
		<canvas id="testcanvas" width="520" height="300"></canvas>
		<br />
		<label>#DATA</label>
		<label id="rateLabel">#DATA</label>
	</div>

	<div id="tradeDiv" class="four columns panel">
		<%= render :partial => "trade", :object  => @currencies %>
	</div>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag "bootstrap.min" %>
<%= javascript_include_tag "bootstrap.min" %>

<h1>User #index</h1>

<div class="row">
	<h4>#My Account</h4>
	<div class="twelve columns panel callout radius">
		<div class="row">
            <div class="six columns">
                <h5>Info</h5>
                <label style="color: #fff" >Firstname: <strong><%= @user.firstname %></strong></label>
                <label style="color: #fff" >Lastname:  <strong><%= @user.lastname %></strong> </label>
                <label style="color: #fff" >Email: <strong><%= @user.email %></strong> </label>
            </div>
            <div class="six columns">
                <h5>My wallet</h5>
                <% for currency in @user.currencies %>
                	<label style="color: #fff" > <%= currency["name"] %>: <strong><%= currency["number"] %></strong> </label>
                <% end %>
            </div>
	    </div>
</div>

<div class="row">
	<div class="twelve columns">
		<h4>#Transactions</h4>
        <table class="table table-striped">
            <thead>
              <tr>
                <th>Action</th>
                <th>Amount (f)</th>
                <th>Currency (f)</th>
                <th>Rate (f)</th>
                <th>Amount (t)</th>
                <th>Currency (t)</th>
                <th>Rate (t)</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
           	  <% for transaction in @transactions %>
               <tr>
                <td><%= transaction.action %></td>
                <td><strong><%= transaction.amount_from %></strong></td>
                <td><%= transaction.currency_from %></td>
                <td><%= transaction.rate_from %></td>
                <td><strong><%= transaction.amount_to %></strong></td>
                <td><%= transaction.currency_to %></td>
                <td><%= transaction.rate_to %></td>
                <td><%= transaction.date %></td>
               </tr>              
              <% end %>
            </tbody>
        </table>
	</div>
	
</div>

app/views/users/new.html.erb
<h1>User #new</h1>

<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div class="error_messages">
	<h2>Form is invalid</h2>
	<ul>
		<% for message in @user.errors.full_messages %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="panel">
	<h4>Create a new account</h4>
	<div class="row">
		<div class="four columns offset-by-one">
			<p>
				<%= f.label :firstname %>
				<%= f.text_field :firstname %>
			</p>
			<p>
				<%= f.label :lastname %>
				<%= f.text_field :lastname %>
			</p>
			<p>
				<%= f.label :email %>
				<%= f.text_field :email %>
			</p>
			<p>
				<%= f.label :password %>
				<%= f.password_field :password %>
			</p>
		</div>
		<div class="four column offset-by-two end">

			<% for currency in @refcurrencies %>

			<%= f.fields_for :nested_currencies do |fl| %>
			<p>
				<%= fl.label :name, currency.name %>
				<%= fl.text_field :number %>
				<%= fl.hidden_field :name, :value => currency.name %>
			</p>
			<% end %>
			<% end %>
			<p>
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation %>
			</p>
		</div>
	</div>
	<div class="row">
		<div class="two columns offset-by-nine">
			<%= f.submit "Create!", :class =>"radius button right" %>
		</div>
	</div>
</div>
<% end %>